### PR TITLE
danDev -> Develop 

### PR DESCRIPTION
**Pull request by dansweet1**
Check these and let me know what you think. I'm not sure the withdrawal reason array is formatted correctly with little to no documentation to go off of.

### CODE REVIEW

**Comment by dansweet1** [comment]
@byerc I believe I corrected the value mapping for all of the methods Y-->True N-->False blank-->blank(let me know if I'm getting the right idea).

**Comment by dansweet1** [comment]
Removed Underscores from method names.

**Comment by beckysteele** [comment]
@byerc, based on your review with @dansweet1, is this resolved?

**Comment by byerc** [comment]
Resolved. This can be tested whenever you and Caroline workout a testing
plan.

**Comment by beckysteele** [comment]
Thanks @byerc!

**Pull request merged**
